/// Translation tables for English (LTR) and Arabic (RTL).
///
/// Lookups go through [AppLocalizations.t]. Missing keys fall back to English,
/// then to the raw key — so the UI never shows a blank string.
class AppStrings {
  AppStrings._();

  static const Map<String, String> en = {
    'app_name': 'CarCare Pro',
    'app_tagline': 'Your vehicle, perfectly maintained',

    // Generic
    'skip': 'Skip',
    'next': 'Next',
    'get_started': 'Get Started',
    'continue': 'Continue',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'done': 'Done',
    'retry': 'Retry',
    'search': 'Search',
    'all': 'All',
    'optional': 'Optional',
    'required_field': 'This field is required',
    'loading': 'Loading…',
    'see_all': 'See all',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'days_ago': 'days ago',
    'in_days': 'in {n} days',
    'overdue': 'Overdue',
    'due_soon': 'Due soon',
    'up_to_date': 'Up to date',
    'km': 'km',
    'liter': 'L',
    'currency': 'SAR',

    // Onboarding
    'ob1_title': 'Maintenance, Tracked',
    'ob1_body': 'Log every oil change, filter and brake job. Never miss a service again.',
    'ob2_title': 'Fuel Analytics',
    'ob2_body': 'Understand your consumption with km/L, cost-per-km and monthly trends.',
    'ob3_title': 'Smart Notifications',
    'ob3_body': 'Get reminded before insurance, license and maintenance fall due.',
    'ob4_title': 'Vehicle Health',
    'ob4_body': 'A live health score from oil, tyres, battery and insurance — at a glance.',

    // Auth
    'sign_in': 'Sign In',
    'sign_up': 'Sign Up',
    'login': 'Log In',
    'register': 'Create Account',
    'welcome_back': 'Welcome back',
    'create_account_title': 'Create your account',
    'login_subtitle': 'Sign in to sync your garage',
    'register_subtitle': 'Start tracking your vehicles today',
    'full_name': 'Full Name',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot password?',
    'forgot_password_title': 'Reset password',
    'forgot_password_body': "Enter your email and we'll send you a reset link.",
    'send_reset_link': 'Send Reset Link',
    'reset_sent': 'Reset link sent. Check your inbox.',
    'no_account': "Don't have an account?",
    'have_account': 'Already have an account?',
    'or_continue_with': 'or continue with',
    'continue_google': 'Continue with Google',
    'continue_apple': 'Continue with Apple',
    'verify_email_title': 'Verify your email',
    'verify_email_body': 'We sent a verification link to {email}. Verify to secure your account.',
    'resend_email': 'Resend email',
    'i_verified': "I've verified",
    'invalid_email': 'Enter a valid email',
    'weak_password': 'Password must be at least 6 characters',
    'password_mismatch': 'Passwords do not match',
    'logout': 'Log Out',
    'logout_confirm': 'Are you sure you want to log out?',
    'auth_failed': 'Authentication failed. Please try again.',

    // Navigation
    'nav_home': 'Home',
    'nav_maintenance': 'Service',
    'nav_fuel': 'Fuel',
    'nav_expenses': 'Expenses',
    'nav_more': 'More',

    // Dashboard
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'vehicle_health': 'Vehicle Health',
    'oil_health': 'Oil',
    'battery_health': 'Battery',
    'tire_health': 'Tyres',
    'insurance_status': 'Insurance',
    'current_mileage': 'Mileage',
    'fuel_economy': 'Economy',
    'upcoming_service': 'Next Service',
    'monthly_expenses': 'This Month',
    'quick_stats': 'Quick Stats',
    'quick_actions': 'Quick Actions',
    'log_fuel': 'Log Fuel',
    'add_service': 'Add Service',
    'add_expense': 'Add Expense',
    'ai_advisor': 'AI Advisor',
    'no_vehicle_title': 'Add your first vehicle',
    'no_vehicle_body': 'Create a vehicle to unlock your dashboard, health score and reminders.',
    'add_vehicle': 'Add Vehicle',
    'upcoming_reminders': 'Upcoming Reminders',
    'no_reminders': 'Nothing due soon. You are all set!',

    // Vehicles
    'my_vehicles': 'My Garage',
    'vehicle_details': 'Vehicle Details',
    'switch_vehicle': 'Switch Vehicle',
    'brand': 'Brand',
    'model': 'Model',
    'year': 'Year',
    'trim': 'Trim',
    'engine': 'Engine',
    'fuel_type': 'Fuel Type',
    'transmission': 'Transmission',
    'plate_number': 'Plate Number',
    'vin': 'VIN',
    'vehicle_image': 'Vehicle Image',
    'petrol': 'Petrol',
    'diesel': 'Diesel',
    'electric': 'Electric',
    'hybrid': 'Hybrid',
    'automatic': 'Automatic',
    'manual': 'Manual',
    'cvt': 'CVT',
    'edit_vehicle': 'Edit Vehicle',
    'delete_vehicle_confirm': 'Delete this vehicle and all its records?',

    // Maintenance
    'maintenance': 'Maintenance',
    'maintenance_timeline': 'Service Timeline',
    'service_history': 'Service History',
    'last_change_date': 'Last Change Date',
    'last_change_mileage': 'Last Change Mileage',
    'next_due_mileage': 'Next Due Mileage',
    'next_due_date': 'Next Due Date',
    'notes': 'Notes',
    'cost': 'Cost',
    'invoice_images': 'Invoice Images',
    'engine_oil': 'Engine Oil',
    'oil_filter': 'Oil Filter',
    'air_filter': 'Air Filter',
    'cabin_filter': 'Cabin Filter',
    'spark_plugs': 'Spark Plugs',
    'brake_pads': 'Brake Pads',
    'brake_fluid': 'Brake Fluid',
    'coolant': 'Coolant',
    'timing_belt': 'Timing Belt',
    'battery': 'Battery',
    'tires': 'Tyres',
    'transmission_oil': 'Transmission Oil',
    'mark_done': 'Mark as Done',
    'log_service': 'Log Service',
    'no_service_title': 'No service logged',
    'no_service_body': 'Log your first service to start tracking maintenance.',

    // Fuel
    'fuel': 'Fuel',
    'fuel_log': 'Fuel Log',
    'odometer': 'Odometer',
    'liters': 'Liters',
    'gas_station': 'Gas Station',
    'price_per_liter': 'Price / L',
    'km_per_liter': 'km / L',
    'avg_consumption': 'Avg. Consumption',
    'cost_per_km': 'Cost / km',
    'monthly_fuel': 'Monthly Fuel',
    'yearly_fuel': 'Yearly Fuel',
    'add_fuel': 'Add Fuel Entry',
    'no_fuel_title': 'No fuel entries',
    'no_fuel_body': 'Log a fill-up to see your consumption analytics.',

    // Expenses
    'expenses': 'Expenses',
    'expense': 'Expense',
    'add_expense_title': 'Add Expense',
    'category': 'Category',
    'amount': 'Amount',
    'date': 'Date',
    'cat_fuel': 'Fuel',
    'cat_maintenance': 'Maintenance',
    'cat_insurance': 'Insurance',
    'cat_parking': 'Parking',
    'cat_carwash': 'Car Wash',
    'cat_registration': 'Registration',
    'cat_fines': 'Fines',
    'cat_accessories': 'Accessories',
    'cat_other': 'Other',
    'monthly_report': 'Monthly Report',
    'yearly_report': 'Yearly Report',
    'total_spent': 'Total Spent',
    'by_category': 'By Category',
    'no_expense_title': 'No expenses yet',
    'no_expense_body': 'Track parking, fines, accessories and more.',

    // Documents
    'documents': 'Documents',
    'add_document': 'Add Document',
    'doc_license': 'Vehicle License',
    'doc_insurance': 'Insurance',
    'doc_inspection': 'Inspection',
    'doc_invoice': 'Invoice',
    'doc_receipt': 'Receipt',
    'expires_on': 'Expires on',
    'no_docs_title': 'No documents',
    'no_docs_body': 'Securely store your license, insurance and receipts.',
    'expiry_date': 'Expiry Date',

    // Insurance & license
    'insurance_license': 'Insurance & License',
    'insurance_expiry': 'Insurance Expiry',
    'license_expiry': 'License Expiry',
    'inspection_date': 'Inspection Date',

    // Analytics
    'analytics': 'Analytics',
    'fuel_usage': 'Fuel Usage',
    'monthly_spending': 'Monthly Spending',
    'maintenance_costs': 'Maintenance Costs',
    'cost_trends': 'Cost Trends',
    'this_year': 'This Year',
    'spending_breakdown': 'Spending Breakdown',

    // AI Advisor
    'advisor_title': 'AI Maintenance Advisor',
    'advisor_subtitle': 'Personalised recommendations from your vehicle history',
    'recommendation': 'Recommendation',
    'analyze': 'Analyze My Vehicle',
    'advisor_no_data': 'Add a vehicle and some service history to get tailored advice.',
    'priority_high': 'High',
    'priority_medium': 'Medium',
    'priority_low': 'Low',

    // Profile & settings
    'profile': 'Profile',
    'settings': 'Settings',
    'account': 'Account',
    'vehicles_count': 'Vehicles',
    'appearance': 'Appearance',
    'language': 'Language',
    'theme': 'Theme',
    'light_mode': 'Light',
    'dark_mode': 'Dark',
    'system_mode': 'System',
    'arabic': 'العربية',
    'english': 'English',
    'notifications': 'Notifications',
    'notification_settings': 'Notification Settings',
    'reminder_timing': 'Reminder Timing',
    'days_before': '{n} days before',
    'data': 'Data',
    'data_export': 'Export Data',
    'backup_restore': 'Backup & Restore',
    'backup': 'Backup',
    'restore': 'Restore',
    'delete_account': 'Delete Account',
    'delete_account_confirm': 'This permanently deletes your account and all data. Continue?',
    'about': 'About',
    'version': 'Version',
    'edit_profile': 'Edit Profile',
    'enable_notifications': 'Enable Notifications',
    'reminder_oil': 'Oil Change',
    'reminder_maintenance': 'Maintenance Due',
    'reminder_insurance': 'Insurance Expiry',
    'reminder_license': 'License Expiry',
    'reminder_battery': 'Battery Check',
    'reminder_tires': 'Tyre Replacement',

    // Misc
    'saved': 'Saved successfully',
    'deleted': 'Deleted',
    'offline_mode': 'Offline mode — changes are saved locally',
    'synced': 'Synced',
  };

  static const Map<String, String> ar = {
    'app_name': 'صياناتي',
    'app_tagline': 'سيارتك في أفضل حالاتها',

    'skip': 'تخطٍ',
    'next': 'التالي',
    'get_started': 'ابدأ الآن',
    'continue': 'متابعة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة',
    'done': 'تم',
    'retry': 'إعادة المحاولة',
    'search': 'بحث',
    'all': 'الكل',
    'optional': 'اختياري',
    'required_field': 'هذا الحقل مطلوب',
    'loading': 'جارٍ التحميل…',
    'see_all': 'عرض الكل',
    'today': 'اليوم',
    'yesterday': 'أمس',
    'days_ago': 'يوماً مضى',
    'in_days': 'خلال {n} يوم',
    'overdue': 'متأخرة',
    'due_soon': 'قريباً',
    'up_to_date': 'محدثة',
    'km': 'كم',
    'liter': 'لتر',
    'currency': 'ر.س',

    'ob1_title': 'تتبّع الصيانة',
    'ob1_body': 'سجّل كل تغيير زيت وفلتر وفرامل، ولا تفوّت موعد صيانة بعد اليوم.',
    'ob2_title': 'تحليلات الوقود',
    'ob2_body': 'افهم استهلاكك عبر كم/لتر، والتكلفة لكل كيلومتر، والاتجاهات الشهرية.',
    'ob3_title': 'تنبيهات ذكية',
    'ob3_body': 'تذكير قبل انتهاء التأمين والرخصة ومواعيد الصيانة.',
    'ob4_title': 'صحة المركبة',
    'ob4_body': 'مؤشر صحة حيّ من الزيت والإطارات والبطارية والتأمين بلمحة واحدة.',

    'sign_in': 'تسجيل الدخول',
    'sign_up': 'إنشاء حساب',
    'login': 'دخول',
    'register': 'إنشاء حساب',
    'welcome_back': 'مرحباً بعودتك',
    'create_account_title': 'أنشئ حسابك',
    'login_subtitle': 'سجّل الدخول لمزامنة سياراتك',
    'register_subtitle': 'ابدأ بتتبّع سياراتك اليوم',
    'full_name': 'الاسم الكامل',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'confirm_password': 'تأكيد كلمة المرور',
    'remember_me': 'تذكّرني',
    'forgot_password': 'نسيت كلمة المرور؟',
    'forgot_password_title': 'إعادة تعيين كلمة المرور',
    'forgot_password_body': 'أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين.',
    'send_reset_link': 'إرسال رابط الإعادة',
    'reset_sent': 'تم إرسال الرابط، تحقق من بريدك.',
    'no_account': 'ليس لديك حساب؟',
    'have_account': 'لديك حساب بالفعل؟',
    'or_continue_with': 'أو تابع عبر',
    'continue_google': 'المتابعة عبر Google',
    'continue_apple': 'المتابعة عبر Apple',
    'verify_email_title': 'تأكيد بريدك',
    'verify_email_body': 'أرسلنا رابط تأكيد إلى {email}. أكّد لتأمين حسابك.',
    'resend_email': 'إعادة الإرسال',
    'i_verified': 'لقد أكّدت',
    'invalid_email': 'أدخل بريداً صحيحاً',
    'weak_password': 'كلمة المرور 6 أحرف على الأقل',
    'password_mismatch': 'كلمتا المرور غير متطابقتين',
    'logout': 'تسجيل الخروج',
    'logout_confirm': 'هل تريد بالتأكيد تسجيل الخروج؟',
    'auth_failed': 'فشل تسجيل الدخول، حاول مجدداً.',

    'nav_home': 'الرئيسية',
    'nav_maintenance': 'الصيانة',
    'nav_fuel': 'الوقود',
    'nav_expenses': 'المصاريف',
    'nav_more': 'المزيد',

    'good_morning': 'صباح الخير',
    'good_afternoon': 'مساء الخير',
    'good_evening': 'مساء الخير',
    'vehicle_health': 'صحة المركبة',
    'oil_health': 'الزيت',
    'battery_health': 'البطارية',
    'tire_health': 'الإطارات',
    'insurance_status': 'التأمين',
    'current_mileage': 'العدّاد',
    'fuel_economy': 'الاقتصاد',
    'upcoming_service': 'الصيانة القادمة',
    'monthly_expenses': 'هذا الشهر',
    'quick_stats': 'إحصائيات سريعة',
    'quick_actions': 'إجراءات سريعة',
    'log_fuel': 'تعبئة وقود',
    'add_service': 'إضافة صيانة',
    'add_expense': 'إضافة مصروف',
    'ai_advisor': 'المستشار الذكي',
    'no_vehicle_title': 'أضف سيارتك الأولى',
    'no_vehicle_body': 'أنشئ سيارة لتفعيل لوحة المعلومات ومؤشر الصحة والتذكيرات.',
    'add_vehicle': 'إضافة سيارة',
    'upcoming_reminders': 'تذكيرات قادمة',
    'no_reminders': 'لا شيء مستحق قريباً. كل شيء جاهز!',

    'my_vehicles': 'مرآبي',
    'vehicle_details': 'تفاصيل المركبة',
    'switch_vehicle': 'تبديل المركبة',
    'brand': 'الماركة',
    'model': 'الطراز',
    'year': 'السنة',
    'trim': 'الفئة',
    'engine': 'المحرك',
    'fuel_type': 'نوع الوقود',
    'transmission': 'ناقل الحركة',
    'plate_number': 'رقم اللوحة',
    'vin': 'رقم الهيكل',
    'vehicle_image': 'صورة المركبة',
    'petrol': 'بنزين',
    'diesel': 'ديزل',
    'electric': 'كهربائي',
    'hybrid': 'هجين',
    'automatic': 'أوتوماتيك',
    'manual': 'يدوي',
    'cvt': 'CVT',
    'edit_vehicle': 'تعديل المركبة',
    'delete_vehicle_confirm': 'حذف هذه المركبة وكل سجلاتها؟',

    'maintenance': 'الصيانة',
    'maintenance_timeline': 'خط زمني للصيانة',
    'service_history': 'سجل الصيانة',
    'last_change_date': 'تاريخ آخر تغيير',
    'last_change_mileage': 'عدّاد آخر تغيير',
    'next_due_mileage': 'العدّاد القادم',
    'next_due_date': 'الموعد القادم',
    'notes': 'ملاحظات',
    'cost': 'التكلفة',
    'invoice_images': 'صور الفاتورة',
    'engine_oil': 'زيت المحرك',
    'oil_filter': 'فلتر الزيت',
    'air_filter': 'فلتر الهواء',
    'cabin_filter': 'فلتر المكيف',
    'spark_plugs': 'البواجي',
    'brake_pads': 'تيل الفرامل',
    'brake_fluid': 'زيت الفرامل',
    'coolant': 'سائل التبريد',
    'timing_belt': 'سير التوقيت',
    'battery': 'البطارية',
    'tires': 'الإطارات',
    'transmission_oil': 'زيت الجير',
    'mark_done': 'وضع علامة كمنجز',
    'log_service': 'تسجيل صيانة',
    'no_service_title': 'لا توجد صيانة',
    'no_service_body': 'سجّل أول صيانة لبدء التتبّع.',

    'fuel': 'الوقود',
    'fuel_log': 'سجل الوقود',
    'odometer': 'العدّاد',
    'liters': 'اللترات',
    'gas_station': 'المحطة',
    'price_per_liter': 'سعر اللتر',
    'km_per_liter': 'كم / لتر',
    'avg_consumption': 'متوسط الاستهلاك',
    'cost_per_km': 'التكلفة / كم',
    'monthly_fuel': 'وقود الشهر',
    'yearly_fuel': 'وقود السنة',
    'add_fuel': 'إضافة تعبئة',
    'no_fuel_title': 'لا توجد تعبئات',
    'no_fuel_body': 'سجّل تعبئة لرؤية تحليلات الاستهلاك.',

    'expenses': 'المصاريف',
    'expense': 'مصروف',
    'add_expense_title': 'إضافة مصروف',
    'category': 'الفئة',
    'amount': 'المبلغ',
    'date': 'التاريخ',
    'cat_fuel': 'وقود',
    'cat_maintenance': 'صيانة',
    'cat_insurance': 'تأمين',
    'cat_parking': 'مواقف',
    'cat_carwash': 'غسيل',
    'cat_registration': 'تسجيل',
    'cat_fines': 'مخالفات',
    'cat_accessories': 'إكسسوارات',
    'cat_other': 'أخرى',
    'monthly_report': 'تقرير شهري',
    'yearly_report': 'تقرير سنوي',
    'total_spent': 'إجمالي المصروف',
    'by_category': 'حسب الفئة',
    'no_expense_title': 'لا مصاريف بعد',
    'no_expense_body': 'تتبّع المواقف والمخالفات والإكسسوارات وغيرها.',

    'documents': 'المستندات',
    'add_document': 'إضافة مستند',
    'doc_license': 'رخصة المركبة',
    'doc_insurance': 'التأمين',
    'doc_inspection': 'الفحص الدوري',
    'doc_invoice': 'فاتورة',
    'doc_receipt': 'إيصال',
    'expires_on': 'ينتهي في',
    'no_docs_title': 'لا مستندات',
    'no_docs_body': 'خزّن رخصتك وتأمينك وإيصالاتك بأمان.',
    'expiry_date': 'تاريخ الانتهاء',

    'insurance_license': 'التأمين والرخصة',
    'insurance_expiry': 'انتهاء التأمين',
    'license_expiry': 'انتهاء الرخصة',
    'inspection_date': 'موعد الفحص',

    'analytics': 'التحليلات',
    'fuel_usage': 'استهلاك الوقود',
    'monthly_spending': 'الإنفاق الشهري',
    'maintenance_costs': 'تكاليف الصيانة',
    'cost_trends': 'اتجاهات التكلفة',
    'this_year': 'هذا العام',
    'spending_breakdown': 'توزيع الإنفاق',

    'advisor_title': 'مستشار الصيانة الذكي',
    'advisor_subtitle': 'توصيات مخصّصة من سجل سيارتك',
    'recommendation': 'التوصية',
    'analyze': 'حلّل سيارتي',
    'advisor_no_data': 'أضف سيارة وبعض سجلات الصيانة للحصول على نصائح مخصّصة.',
    'priority_high': 'عالية',
    'priority_medium': 'متوسطة',
    'priority_low': 'منخفضة',

    'profile': 'الملف الشخصي',
    'settings': 'الإعدادات',
    'account': 'الحساب',
    'vehicles_count': 'السيارات',
    'appearance': 'المظهر',
    'language': 'اللغة',
    'theme': 'السمة',
    'light_mode': 'فاتح',
    'dark_mode': 'داكن',
    'system_mode': 'النظام',
    'arabic': 'العربية',
    'english': 'English',
    'notifications': 'الإشعارات',
    'notification_settings': 'إعدادات الإشعارات',
    'reminder_timing': 'توقيت التذكير',
    'days_before': 'قبل {n} يوم',
    'data': 'البيانات',
    'data_export': 'تصدير البيانات',
    'backup_restore': 'النسخ والاستعادة',
    'backup': 'نسخ احتياطي',
    'restore': 'استعادة',
    'delete_account': 'حذف الحساب',
    'delete_account_confirm': 'سيؤدي هذا إلى حذف حسابك وكل بياناتك نهائياً. متابعة؟',
    'about': 'حول التطبيق',
    'version': 'الإصدار',
    'edit_profile': 'تعديل الملف',
    'enable_notifications': 'تفعيل الإشعارات',
    'reminder_oil': 'تغيير الزيت',
    'reminder_maintenance': 'صيانة مستحقة',
    'reminder_insurance': 'انتهاء التأمين',
    'reminder_license': 'انتهاء الرخصة',
    'reminder_battery': 'فحص البطارية',
    'reminder_tires': 'تبديل الإطارات',

    'saved': 'تم الحفظ بنجاح',
    'deleted': 'تم الحذف',
    'offline_mode': 'وضع عدم الاتصال — تُحفظ التغييرات محلياً',
    'synced': 'تمت المزامنة',
  };
}
